# kubectl create deployment hello-spring --image=neilghosh/hello-spring
# kubectl expose deployment hello-spring --type=NodePort --port 80 --target-port 8080
# kubectl scale deployment hello-spring --replicas=3
# kubectl set image deployment/hello-web hello-app=gcr.io/${PROJECT_ID}/hello-app:v2
# minikube service hello-spring --url

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app
  template:
    metadata:
      labels: 
        app: app
    spec:
      containers:
        - name: app
          image: neilghosh/hello-spring
          ports:
            - name: http
              containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: hello-spring
  labels:
    app: app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: app
---
                           